---
title: "Integrating black-swan events into fisheries science"
author:
  - Sean C. Anderson
date: "`r format(Sys.time(), '%B %d %Y')`"
output:
    bookdown::html_document2:
      fig_caption: yes
bibliography: references.bib
csl: "../templates/cjfas.csl"
abstract: |
  Text of abstract
---

```{r, setup, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  fig.path = "../figures/"
)

# library(surprise)
```

<!--

[@holling1985]

[@hilborn1987a]

[@mangel1994]

[@taleb2007]

[@sornette2002; @sornette2009]

[@lindenmayer2018] (*Conservation conundrums and the challenges of managing unexplained declines of multiple species*)

[@nunez2012]

-->

<!-- Black swans are highly improbable events with major consequences that are
often only considered predictable in retrospect. Such events define the world
around us — from banking collapses to earthquakes. In fisheries, black-swan
events could refer, for example, to abrupt declines in fish abundance or
massive recruitment events. In this talk, I consider how we can integrate the
concept into fisheries science. I explore why we should expect black-swan
events and why climate change is likely to increase their occurrence. I compare
similarities and differences between black swans and the related ecological
concepts of regime shifts, tipping points, and mass-mortality events, and
explore how the concept can be translated into statistical approaches through
the use of extreme-value distributions, power laws, and non-linearity. Above
all else, black swans necessitate a change in perspective; the goal is not
usually to predict such events but to make models and management robust to
them. I therefore suggest strategies for how we can introduce such robustness
to fisheries science, including incorporating heavy-tailed distributions into
process error and projections, integrating extreme events into closed-loop
simulations, considering ensembles of stock assessment models with different
structural assumptions, and automating the rapid visualization of fisheries
data and model fits. -->

# Introduction

Black swans are highly improbable events with major consequences that are often
only considered predictable in retrospect. Such events define the world around
us---from banking collapses to earthquakes. *some examples here, e.g.
Fukushima, ...* A rich field of mathematics, statistics, and philosophy has
developed around the concept of extremes, black-swan events, and even 'dragon
kings' (extreme but predictable outliers) with applications mostly to finance
(REF), natural disasters (REF), and ... (REF).

*or*

Uncertainty is a pervasive element of natural resource management. But there
exist many types of uncertainty. Seemingly unlikely but highly impactful
events---black swans or ecological surprises---are amongst the hardest to
predict...

In natural resource management, there are many iconic examples ...

- Northern cod
- Fraser River sockeye salmon
- sea lamprey

Black-swan events and surprise unite many related themes and ecology and
natural resource management. @taleb2007 defines black-swan events as requiring
a triplet: rarity, extreme impact, and retrospective predictability. ...

- (catastrophic) regime shifts [@scheffer2003]
- extreme climatic events [@smith2011c] [e.g. @smale2013]
- mass mortality events [@fey2015]
- ecological surprise [@doak2008] [@filbee-dexter2017]
- bifurcations and tipping points
- ...

Figure: Venn diagram of related concepts

<!-- could say something about black swans vs. surprise and how one captures
attention, one focuses on the *event* but in a scary/negative way... the other
focuses on the human element and I think emphasizes the opportunity to learn
-->

# The increasing relevance of surprise to fish and fisheries

We should expect black-swan events and surprise to be an important feature of
fish and fisheries. Marine ecosystems contain an enormous number of potentially
nonlinear interactions.

Our ability to observe and capture marine ecosystem and fisheries dynamics is
limited---perhaps even more so than most other forms of natural resource
management.

The take-home message of the black swan concerns not just that black swans
happen, but where they can happen. Scalable versus non-scalable events...

- bakers vs. authors
- salmon size versus salmon returns
- population growth versus population mortality
- but fish recruitment...

<!-- or put this paragraph elsewhere -->

<!-- ecological memory and autocorrelation -->

Surprises are likely to become even more ubiquitous in the management of
aquatic resources with climate change.

*or*

Surprise is a concept more relevant now than ever before because of climate
change.

# Evidence for black-swan events in aquatic systems

[@batt2017]

[@doak2008]

[@fey2015]

[@anderson2017c]

[@young1994]?

# Challenges and solutions

## Try to avoid surprise

- experiments with trends *and* events? [@jentsch2007]

## Embed surprise into models

[@anderson2017c]

[@anderson2019]

[@chen1999]

[@ward2007]

[@gaines1993]

[@batt2017]

## Make the management system robust to surprise

[@anderson2017b]

## Detect and react quickly to surprise

[@charles1998] *Living with uncertainty in fisheries: analytical methods, management priorities and the Canadian groundfishery experience*

[@schneider1998] *Schneider, S.H., Turner, B.L. & Garriga, H.M. (1998). Imaginable surprise in global change science. J. Risk Res., 1, 165–185.* **to read in detail**

[@wintle2010] *Allocating monitoring effort in the face of unknown unknowns*

# Conclusion

Somewhere: [@carpenter2012], [@burgman2012]

# Acknowledgements

\newpage

# Figures

## Probably

1. Venn diagram of related concepts.
1. Press and pulse climate change extremes [@harris2018]?
   Adapt to also have increased variance?
1. Student-t distribution (with and without skew?), mixture distributions, and
   GEV distribution? Each could be associated with a timeseries.

## Other possibilities

1. Predictability of event vs. potential impact figure from presentation?
1. The Precautionary Approach?
1. Could include some diversification figure republished.
1. A figure from @deroba2015?
1. Example from synopsis report of automated reporting? (probably not)

# Tables

## Probably

1. Examples of surprise and extreme events in fish and fisheries? Time, space,
   reaction to management intervention, ...
1. Table summarizing the main challenges and solutions?

## Other possibilities

1. Related concepts, citations, and examples?
1. A table of scalable and non-scalable quantities for fish and fisheries?

\newpage

# References

